[app]
  # change this to your Fly app name
  app = "trainer-database"
  primary_region = "" 

[build]
  image = ""

[deploy]
  release_command = ""

[env]
  DB_DRIVER = "pgsql"
  DB_HOST = ""
  DB_PORT = "5432"
  DB_NAME = ""
  DB_USER = ""
  DB_PASS = ""

[experimental]
  allowed_public_ports = [80]
  auto_rollback = true
